### ISSUE TITLE
Error whilst adding Latitude/Longitude

### ISSUE THREAD

**Issue by craigmate** [tonymyatt/homeassistant-custom-components#1]
HI

I just discovered your custom component, but am having issues added it.

I have downloaded it to my custom_componet folder and rebooted,  I then try to add it as an intergration, however when I put in the lat/long  it fails

In the log file it shows the following error

Traceback (most recent call last):
  File "/config/custom_components/aus_fuel/config_flow.py", line 64, in async_step_user
    self.stations_fuel_types = await validate_input(self.hass, user_input)
  File "/config/custom_components/aus_fuel/config_flow.py", line 39, in validate_input
    result = await hass.async_add_executor_job(api.refresh_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aus_fuel/aus_fuel_api.py", line 34, in refresh_data
    self._fuel_prices = json_data["data"]
KeyError: 'data'

Not sure what i an doing wrong.  I did reduce my decimal point on the lat/long to 3, but it didn't seem to help

Thank You

**Comment by tonymyatt** [comment]
Hi, do you mind private messaging me your coordinates? I suspect the API I am using does not support your location. Also some bad news, the API has been reporting static values for a couple of weeks, confirmed incorrect values by comparing prices with other websites. I am currently looking for an alternative source for the price data. -Tony.

**Comment by craigmate** [comment]
Not sure I can leave a PM on github,  but just for context, I do live in the south east suburbs in Melbourne, so I would think the API would cover where I live.  I also live close to about 3 servo's

but if you are saying the API isn't working, that is annoying as I would like to be able to get fuel prices for around my area.

Thanks for the component, 
Cheeers

**Comment by tonymyatt** [comment]
So done some more research, Victoria isn't supported by the API I am using. When I find an alternative source for the data which hopefully is for all of Australia, I will let you know.

**Comment by alexisspencer** [comment]
Hi, I'm also from Victoria and would be interested in knowing when you have an alternative source of data too. Thanks

**Comment by alexisspencer** [comment]
Just to add, I can see this site has an API available if you register:
https://fuelprice.io/api/documentation/
