### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by spusuf** [tonymyatt/homeassistant-custom-components#2]
Copied the folder into custom components, selected the integration in home assistant and put in latitude and longitude, occasionally get to second screen and have tried both options (station and fuel type) but no further configuration is possible? Am I missing something? Is there meant to be another screen? No sensor, no state, no attributes.

**Comment by AndrewD79** [comment]
> Copied the folder into custom components, selected the integration in home assistant and put in latitude and longitude, occasionally get to second screen and have tried both options (station and fuel type) but no further configuration is possible? Am I missing something? Is there meant to be another screen? No sensor, no state, no attributes.

did you ever get this to work? having the same problem. i entered the distance and lat/long... but not seeing any entities discovered. i notied in the python script that it was set to poll hourly - but would have thought it would poll immediately upon configuration... changing this value didn't help.

**Comment by spusuf** [comment]
> > Copied the folder into custom components, selected the integration in home assistant and put in latitude and longitude, occasionally get to second screen and have tried both options (station and fuel type) but no further configuration is possible? Am I missing something? Is there meant to be another screen? No sensor, no state, no attributes.
> 
> did you ever get this to work? having the same problem. i entered the distance and lat/long... but not seeing any entities discovered. i notied in the python script that it was set to poll hourly - but would have thought it would poll immediately upon configuration... changing this value didn't help.

I did not, ended up using a plugin available on HACS which just tells me the cheapest in Australia for each fuel type and basing my judgement on that, quite a shame

**Comment by tonymyatt** [comment]
Hi Guys - the aus_fuel integration is broken until i can find another free datasource for the prices.

**Comment by spusuf** [comment]
Hey there's multiple API services. 
There's an Australia wide one: https://fuelprice.io/api/
Theres also official government ones for QLD, NSW, and TAS, maybe a few more. But I think the Australia wide one looks the most promising as it gives all the information straight on the website.
